-- School Teacher Management System Schema

DROP TABLE IF EXISTS MARKS;
DROP TABLE IF EXISTS SUBJECT;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS TEACHER;
DROP TABLE IF EXISTS CLASS;

-- CLASS TABLE
CREATE TABLE CLASS (
    ClassID INT AUTO_INCREMENT PRIMARY KEY,
    ClassName VARCHAR(50) NOT NULL UNIQUE
);

-- TEACHER TABLE
CREATE TABLE TEACHER (
    TeacherID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Subject VARCHAR(50)
);

-- STUDENT TABLE
CREATE TABLE STUDENT (
    StudentID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Age INT,
    ClassID INT,
    FOREIGN KEY (ClassID) REFERENCES CLASS(ClassID)
    ON DELETE SET NULL
);

-- SUBJECT TABLE
CREATE TABLE SUBJECT (
    SubjectID INT AUTO_INCREMENT PRIMARY KEY,
    SubjectName VARCHAR(50) NOT NULL,
    TeacherID INT,
    FOREIGN KEY (TeacherID) REFERENCES TEACHER(TeacherID)
    ON DELETE SET NULL
);

-- MARKS TABLE
CREATE TABLE MARKS (
    MarkID INT AUTO_INCREMENT PRIMARY KEY,
    StudentID INT,
    SubjectID INT,
    Score INT CHECK (Score BETWEEN 0 AND 100),
    FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID)
    ON DELETE CASCADE,
    FOREIGN KEY (SubjectID) REFERENCES SUBJECT(SubjectID)
    ON DELETE CASCADE
);